# Classification

In [1]:
#KNN
#logistic regression 
#SVM
#Naive Bayes

In [2]:
'''there are some scoring methods..
accuracy score
recall
precision
roc_auc_score
'''

'there are ssome scoring methods..\naccuracy score\nrecall\nprecision\nroc_auc_score\n'

# KNN

In [3]:
'''the principle behind nearest neighbour method is to find a predefined number of training samples closest in distance
to the new point,and predict the label from these.'''

'the principle behind nearest neighbour method is to find a predefined number of traing samples closest in distance\nto the new point,and predict the label from these.'

'''it has one of the simplest learning strategy :given a new unknown observation look up in your reference database which one have the closest features and assign the predominant class
    the distancce can,in general be any metrics ,measure :standard euclidean distance is the most common choice.'''

In [4]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [5]:
iris=load_iris()

In [6]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [7]:
knn=KNeighborsClassifier ()

In [8]:
iris.target_names


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris.data.shape

(150, 4)

In [11]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
import numpy as np
import pandas as pd

In [13]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
np.bincount(iris.target)

array([50, 50, 50], dtype=int32)

In [15]:
c={0:'setosa', 1:'versicolor', 2:'virginica'}
#df['target']=[iris.target_names[i] for i in iris.target] another method for mapping...

In [16]:
df['target']=df.target.map(c)

In [17]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [18]:
x=df.iloc[:,:-1].values#-1 excludong last columns
y=iris.target#bcz we changes in df of target column

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=10)#by default test-size is 25 %

In [20]:
x_train.shape

(120, 4)

In [21]:
x_train.ndim

2

In [22]:
x_test.shape

(30, 4)

In [23]:
#ttrain model with training data
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [24]:
y_pred=knn.predict(x_test)

In [25]:
y_pred

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9666666666666667

In [27]:
np.where(y_test!=y_pred)

(array([6], dtype=int32),)

In [28]:
distance=knn.kneighbors(x_test[4].reshape(1,-1),n_neighbors=3, return_distance=True)

In [29]:
distance

(array([[0.14142136, 0.2236068 , 0.2236068 ]]),
 array([[ 61, 110,  73]], dtype=int32))

In [30]:
 y[61],y[110],y[73]

(1, 2, 1)

In [31]:
x_test[4]


array([5. , 3.3, 1.4, 0.2])

In [32]:
y_pred[4]

0

In [33]:
'''knn.score(x_train,y_train)....it will give the score b/w these two beforing fitting
knn.socre(x_test,y_test)'''

'knn.score(x_train,y_train)....it will give the score b/w these two beforing fitting\nknn.socre(x_test,y_test)'

In [34]:
knn.score(x_train,y_train)

0.975

In [35]:
knn.score(x_test,y_test)

0.9666666666666667

In [36]:
accuracy_score(y_test,knn.predict(x_test))

0.9666666666666667

In [38]:
plt.scatter(x_train['sepal length (cm)'],y_train,color='red')   #training data
#plt.scatter(X_test,y_test,color='blue')   #testing data
plt.scatter(x_test['sepal length (cm)'],y_pred,color='blue')   #testing data
plt.plot(x_train['sepal length (cm)'],knn.predict(x_train['sepal length (cm)'].reshape(-1,1)),color='green')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
quest-->when to use which model...??