In [1]:
#Logistic Algorithm 

In [2]:
#logistic regression is  a machine learning classification algorithm taht is used to predict the probability of categorical dependent variable(Y)
#the dependent variable is a binary variable that contains data coded as 1 or 0.

In [3]:
#and also used for multi-classification problem
#logistic regresion model will take the feature values and calculates the probabilities if the probabilityis greater  than or equal to 50% ar epredicted to be in positive class otherwise negative class

In [4]:
#p=1/(1+e^-y)  #logistic function 

In [5]:
from sklearn.datasets import load_iris


In [6]:
iris=load_iris()

In [7]:
x=iris.data[:100]

In [8]:
y=iris.target[:100]

In [9]:
import numpy as np

In [10]:
x.shape

(100, 4)

In [11]:
np.unique(y)

array([0, 1])

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=18)

In [14]:
x_train.shape

(70, 4)

In [15]:
x_test.shape


(30, 4)

In [16]:
log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
b=log_reg.intercept_
b

array([-0.24175445])

In [18]:
m=log_reg.coef_
m

array([[-0.39493934, -1.30935888,  2.07339412,  0.97386647]])

In [19]:
y_pred=log_reg.predict(x_test)
from sklearn.metrics import roc_auc_score

In [20]:
roc_auc_score(y_test,y_pred)

1.0

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
import numpy as np

In [22]:
x_test[0]

array([5.5, 2.3, 4. , 1.3])

In [23]:
#y=sum((log_reg.coef_)*(x_test[0]))+(log_reg.intercept_)

In [24]:
def line(x1,x2,x3,x4):
    y=b[0]+m[0][0]*x1+m[0][1]*x2+m[0][2]*x3+m[0][3]*x4
    return y

In [25]:
def prob(x1,x2,x3,x4):
    value=line(x1,x2,x3,x4)
    return 1/(1+np.exp(-value))

In [26]:
t=x_test[0]

In [27]:
t

array([5.5, 2.3, 4. , 1.3])

In [28]:
y_pred=log_reg.predict(x_test)
y_pred[0]

1

In [29]:
prob(t[0],t[1],t[2],t[3])

0.9842363068773441

In [30]:
np.where(y_pred!=y_test) 

(array([], dtype=int32),)